server:
  port: 8380
capi:
  websocket:
    enabled: true
    server:
      host: localhost
      port: 8381
  oidc:
    provider:
      enabled: false
      host: http://localhost:8080
      realm: /realms/master
      clientId:
      clientSecret: